server:
  port: 8085
spring:
  application:
    name: transfer
  config:
    import:
      - "optional:consul:"
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: transfer
      config:
        enabled: true            # Включаем Consul Config для внешней конфигурации
        defaultContext: application