server:
  port: 8082
spring:
  application:
    name: front
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: bank-ui
            client-secret: ui-client-secret
            scope: openid, profile
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/bank
  config:
    import:
      - "optional:consul:"
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: front
      config:
        enabled: true            # Включаем Consul Config для внешней конфигурации
        defaultContext: application