server:
  port: 8084
spring:
  application:
    name: cash
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/bank
  config:
    import:
      - "optional:consul:"
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: cash
      config:
        enabled: true            # Включаем Consul Config для внешней конфигурации
        defaultContext: application
