server:
  port: 8081

spring:
  application:
    name: accounts
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/bank
      client:
        registration:
          account-service:
            provider: keycloak
            client-id: account-service
            client-secret: TS4tWP4SkqMpeg7XBuM71XuXQKOcS8ml
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/bank
  config:
    import:
      - "optional:consul:"
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: accounts
      config:
        enabled: true            # Включаем Consul Config для внешней конфигурации
        defaultContext: application
  datasource:
    url: jdbc:postgresql://localhost:5432/bankdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: accounts
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
