server:
  port: 8086

spring:
  application:
    name: gatewayapi
  config:
    import:
      - "optional:consul:"
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: gatewayapi
      config:
        enabled: true            # Включаем Consul Config для внешней конфигурации
        defaultContext: application
    gateway:
      mvc:
        routes:
        - id: accounts-api-docs
          uri: http://localhost:8081
          order: 1
          predicates:
            - Path=/api-docs/accounts/**
          filters:
            - RewritePath=/api-docs/accounts/(?<segment>.*),/${segment}
        - id: notifications-api-docs
          uri: http://localhost:8083
          order: 2
          predicates:
            - Path=/api-docs/notifications/**
          filters:
            - RewritePath=/api-docs/notifications/(?<segment>.*),/${segment}
        - id: cash-api-docs
          uri: http://localhost:8084
          order: 3
          predicates:
            - Path=/api-docs/cash/**
          filters:
            - RewritePath=/api-docs/cash/(?<segment>.*),/${segment}
        - id: transfer-api-docs
          uri: http://localhost:8085
          order: 4
          predicates:
            - Path=/api-docs/transfer/**
          filters:
            - RewritePath=/api-docs/transfer/(?<segment>.*),/${segment}
        - id: accounts-service
          uri: http://localhost:8081
          order: 10
          predicates:
            - Path=/api/account/**
        - id: notifications-service
          uri: http://localhost:8083
          order: 20
          predicates:
            - Path=/api/notify/**
        - id: cash-service
          uri: http://localhost:8084
          order: 30
          predicates:
            - Path=/api/cash/**
        - id: transfer-service
          uri: http://localhost:8085
          order: 40
          predicates:
            - Path=/api/transfer/**

springdoc:
  swagger-ui:
    urls:
      - name: accounts
        url: /api-docs/accounts/v3/api-docs
      - name: notifications
        url: /api-docs/notifications/v3/api-docs
      - name: cash
        url: /api-docs/cash/v3/api-docs
      - name: transfer
        url: /api-docs/transfer/v3/api-docs